server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: acnecare-api
  datasource:
    url: "jdbc:mysql://localhost:3306/acnecare"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer_key: "fb886b389ba6cd149a7deef483af664b62ff17776eb0d04a991251c0e4fba92e"
  access-token-valid-duration: 3600 #in seconds : 20 minutes
  refresh-token-valid-duration: 604800 #a week

cors:
  allowed-origins: "http://localhost:5173"